CREATE SCHEMA `SAUDE_DH`;
USE `SAUDE_DH`;

CREATE TABLE `SAUDE_DH`.`PACIENTE`(
`PACIENTE_ID` INT NOT NULL,
`PACIENTE_IDSAUDE` INT NULL,
`PACIENTE_NOME` VARCHAR(50) NULL,
`PACIENTE_SOBRENOME`VARCHAR(100) NULL,
PRIMARY KEY (`PACIENTE_ID`)
);

CREATE TABLE `SAUDE_DH`.`ESPECIALIDADE`(
`ESPECILIDADE_ID` INT NOT NULL,
`ESPECILIDADE_NOME` VARCHAR (100),
PRIMARY KEY (`ESPECILIDADE_ID`)
);

ALTER TABLE `SAUDE_DH`.`ESPECIALIDADE` RENAME COLUMN `ESPECIALIDADE_ID` TO `ESPECILIDADE_ID`;
ALTER TABLE `SAUDE_DH`.`ESPECIALIDADE` RENAME COLUMN `ESPECIALIDADE_NOME` TO `ESPECILIDADE_NOME`;

CREATE TABLE `SAUDE_DH`.`MEDICO`(
`MEDICO_ID` INT NOT NULL,
`MEDICO_NOME` VARCHAR(50) NULL,
`MEDICO_SOBRENOME`VARCHAR(100) NULL,
`MEDICO_ESPECIALIDADE`INT NULL,
PRIMARY KEY (`MEDICO_ID`),
CONSTRAINT `FKESPECIALIDADE` FOREIGN KEY (`MEDICO_ESPECIALIDADE`) REFERENCES `SAUDE_DH`.`ESPECIALIDADE`(`ESPECILIDADE_ID`)
);

CREATE TABLE `SAUDE_DH`.`CONSULTA`(
`CONSULTA_ID` INT NOT NULL,
`PACIENTE_ID`INT NULL,
 `MEDICO_ID` INT NULL,
 `DATA_CONSULTA` DATE NULL,
 `HORA_CONSULTA` TIME NULL,
 PRIMARY KEY (`CONSULTA_ID`),
 CONSTRAINT `FKPACIENTE` FOREIGN KEY (`PACIENTE_ID`) REFERENCES `SAUDE_DH`.`PACIENTE`(`PACIENTE_ID`),
 CONSTRAINT `FKMEDICO` FOREIGN KEY (`MEDICO_ID`) REFERENCES `SAUDE_DH`.`MEDICO`(`MEDICO_ID`) 
 );

